### ISSUE TITLE
always out of memory after some minute

### ISSUE THREAD

**Issue by kangkang59812** [poojahira/image-captioning-bottom-up-top-down#10]
the GPU memory increases along with for-loop when training.

**Comment by OysterSecret** [comment]
Same issue

**Comment by poojahira** [comment]
Hi, I was able to successfully train for > 30 epochs using my university GPU cluster with a memory of 120 GB. The code can probably be optimized to use less memory though.

**Comment by kangkang59812** [comment]
@poojahira thanks for you reply. I have read all the codes, maybe I should consider more about how to optimal.

**Comment by poojahira** [comment]
Yes I agree. Please push improvements to this codebase as well if you come across any.

**Comment by MozhganPourKeshavarz** [comment]
> @poojahira thanks for you reply. I have read all the codes, maybe I should consider more about how to optimal.
Hi @kangkang59812
could you find any solution?

**Comment by fdgfgdfd** [comment]
you can use **torch.cuda.empty_cache()** to release your cache

**Comment by fdgfgdfd** [comment]
loss_d = criterion_dis(scores_d,targets_d.long())
This loss function caused the increasing of the GPU memory while using pytorch-0.4, when I used pytorch-1.1.0, this problem was solved. Maybe it is a bug in pytorch-0.4?
