### ISSUE TITLE
HDF5 file and PKL files

### ISSUE THREAD

**Issue by tong8080** [poojahira/image-captioning-bottom-up-top-down#13]
Hello, I can't download the bottom up image features. Could you give me the download link about the processed HDF5 file, PKL files and JSON file? Thanks!!

**Comment by tong8080** [comment]
or the google drive link about the bottom up image features. Thanks!

**Comment by poojahira** [comment]
The bottom up features are available here: https://imagecaption.blob.core.windows.net/imagecaption/trainval_36.zip

**Comment by tong8080** [comment]
Thanks. I have download it.
