### ISSUE TITLE
Captioning a new image

### ISSUE THREAD

**Issue by piperino11** [poojahira/image-captioning-bottom-up-top-down#17]
If I want generate a caption for my image, where I can find the model fo faster R-ccn for extract the features?

**Comment by ada-dl** [comment]
I am new to deep learning and I would really want to know this as well. How can we run this model, once trained, on a new image, or train on a new dataset? Thank you anyone who can provide some insight on this.

**Comment by poojahira** [comment]
Hi, for a new image, you will need to extract the bottom up features from a Faster RCNN model first before using this codebase.
