### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by lzy119** [poojahira/image-captioning-bottom-up-top-down#18]
hi, I have a problem ,and i need your help. When i was running 'python eval.py', i got a error 
"i = complete_seqs_scores.index(max(complete_seqs_scores))
ValueError: max() arg is an empty sequence
"
Why is the resulting sequence empty？

**Comment by mpourkeshavarz** [comment]
it works for me.
solution : [issue18](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/18)
