### ISSUE TITLE
question about result

### ISSUE THREAD

**Issue by userWangnx** [poojahira/image-captioning-bottom-up-top-down#2]
thanks for the pytorch version source code !
I have run the code and found that the results not get your's result of the evaluation,  specifically,BLEU-4 more less than your's data.
could you please offer model that you have trained done for me?
many thanks!

**Comment by poojahira** [comment]
The model is available here: https://drive.google.com/file/d/10atC8rY7PdhnKW08INO33mEXYUyQ6G0N/view?usp=sharing

**Comment by userWangnx** [comment]
thank you very much !

**Comment by userWangnx** [comment]
Thanks again for the model you provided, but using this model requires a corresponding word file, 
could you please offer the  WORDMAP_coco_5_cap_per_img_5_min_word_freq.json file for training this model？

**Comment by poojahira** [comment]
I don't have the file on me right now. Please go through the 'Data Preparation' section of the README to see how to generate the file.

**Comment by userWangnx** [comment]
I generated this file, but using this file combined with the model you provided did not generate the correct sentence.

**Comment by userWangnx** [comment]
In addition, I tried different files and the model I trained before. The model that generated the correct sentence needs the corresponding word file. Unfortunately, the model I trained did not reach the result you provided.

**Comment by poojahira** [comment]
hmmm not sure why that is...sadly access to my university cluster has been revoked since I graduated so I cannot help you out too much else I would have tested the model file again.
I found a copy of the WORDMAP file on my local machine: link to it is here: https://drive.google.com/file/d/1ikW5oALI0hxbXbPvWHZkM1O3RNTEH3Pf/view?usp=sharing
Hope this helps.

**Comment by userWangnx** [comment]
I am grateful to be able to get your reply, thank you again for the code and documentation provided.

**Comment by poojahira** [comment]
No problem...wish I could help more...hope it works out for you.
